##################################################################
#
#   Elastic Stack: https://github.com/sherifabdlnaby/elastdocker
#
#   $ make setup && sudo sysctl -w vm.max_map_count=262144
#   $ make elk # replace docker.elastic.co/* to elastic
#
##################################################################

services:
  elasticsearch:
    image: bitnami/elasticsearch:8.15.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ../.data/elastic:/bitnami/elasticsearch/data
    networks:
      - localnet

  kibana:
    image: bitnami/kibana:8.17.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
